### ISSUE TITLE
[bug]: 设备中心 UI

### ISSUE THREAD

**Issue by yuxueer** [jim-king-2000/IndustryCamera#18]
### 问题描述
- 列展示太多的情况下，避免标题换行增加滑动条
- 设备区域未显示完整目录

### 您预期的行为
- 不出现标题文字重叠
- 设备区域显示完整目录，例 风场A/风塔1/层1

### 系统表现的行为
![image](https://user-images.githubusercontent.com/89175659/131308042-0d6b9086-0e10-41de-afd3-6745e4cded32.png)

### 辅助信息
- 浏览器版本：Edge/Chrome 92
- 固件版本：v1.0

**Comment by FireWild** [comment]
所有的table都需要做对应的处理

**Comment by Luh10032** [comment]
已修复
